# https://alacritty.org/config-alacritty.html

[window]
startup_mode = "Maximized"

[font]
# normal = { family = "JetBrains Mono", style = "Regular" }
# normal = { family = "NotoMono Nerd Font Mono", style = "Regular" }
normal = { family = "JetBrains Maple Mono", style = "Regular" }
bold = { family = "JetBrains Maple Mono", style = "bold" }
italic = { family = "JetBrains Maple Mono", style = "italic" }
bold_italic = { family = "JetBrains Maple Mono", style = "bold italic" }
size = 14

